apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: doomed-apt
resources:
  - deployment.yaml
  - service-nodeport.yaml
  - ingress.yaml
images:
  - name: mmmmnl/lobotomy_but_front
    newTag: v.1.0
