name: 'ğŸš€ Deploy Frontend to GKE'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  GKE_CLUSTER: doomapt-project-cluster
  GKE_ZONE: asia-southeast1
  K8S_PATH: app/k8s 
  DOCKER_IMAGE_NAME: mmmmnl/lobotomy_but_front

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      backend:
        image: mmmmnl/lobotomycorp:latest 
        ports:
          - 8080:8080
        env:
          SPRING_PROFILES_ACTIVE: dev 
    
    permissions:
       contents: 'read'
       id-token: 'write'

    steps:
    - name: 'ğŸ“¥ Check out code'
      uses: actions/checkout@v4
    
    # - name: 'ğŸ§ª Run Cypress E2E Tests'
    #   uses: cypress-io/github-action@v6
    #   env:
    #     # FORCE the correct URL here to override any defaults
    #     CYPRESS_API_BASE_URL: https://apt.krentiz.dev/api
    #     CYPRESS_baseUrl: https://apt.krentiz.dev
    #   with:
    #     working-directory: app
    #     browser: chrome

    - name: 'ğŸ³ Build the Docker image'
      run: docker build --file app/Dockerfile -t ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} app
      
    - name: 'ğŸ”‘ Docker Hub Login'
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: 'ğŸ“¤ Push Docker Image'
      run: docker push ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
      
    - name: 'ğŸ” Authenticate to GCP (WIF)'
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        
    - name: 'âš™ï¸ Get GKE Credentials'
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        
    - name: 'ğŸ”§ Install Kustomize'
      run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
      
    - name: 'ğŸ“ Update K8s Image Tag'
      run: |
        cd ${{ env.K8S_PATH }}
        ../../kustomize edit set image ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
        
    - name: 'ğŸš€ Deploy Frontend to GKE'
      run: |
        kubectl apply -k ${{ env.K8S_PATH }} --namespace=doomed-apt
        
    - name: 'â³ Wait for Deployment Rollout'
      run: kubectl rollout status deployment/frontend-deployment --namespace=doomed-apt --timeout=5m
